var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "        yyy                              yyyy  yyyyy                            ",
   "      yyyyyyy            yyyyyyy        yyyyyyyyyyyyyyyy                        ",
   "     yyyyyyyyyy        yyyyyyyyyyyyyy    yyyyyyyyyyyyyy                         ",
   "                                                                                ",
   "     !   !          xxx                                                         ",
   "     !              x!x             o o             o                           ",
   "              o     xvx                                                         ",
   "     ^                                          o                               ",
   "             xx                     !                                           ",
   "       o                              xxx             xx                  ^      ",
   "                              xxx                                 o             ",
   "      xx x   xxx   o     xx                                                     ",
   " @          xx x                               !       x!!!!!!x                 ",
   "xxxxx!!!!!!!x  xxxxxxxxxxxx!!!!!!!!!!xxxxxxxxxx!xxxxxxxx!!!!!!xxxxxxxxxx!!!xxxxx",
   "     x!!!!!x               xx!!!!!!xx         x!x                      x!!!x    ",
   "      x!!!x                 x!!!!!x           x!x                      xxxxx    ",
   "      x!!!x  !              x!!!!!x           x!x                               ",
   "       x!x   x              xx!!!xx           x!x                               ",
   "        x                     x!x             xxx                               ",
   "                               x                                                "],
  ["             xxxxxx                                                                                                   ",
   "             x oo                                                                                                     ",
   "             x                                                                                                        ",
   "             x                                                                                                        ",
   "             x      |                                                                                                 ",
   "             x    x                                                                                                   ",
   "             xx   x                                                                                                   ",
   "             x    x                                   yyyyyyy    yyyyyyyy                                             ",
   "             x    x                                   yyyyyyyyyyyyyyyyyyy                                             ",
   "             x    x!!!!!                                 yyyyyyyyyyyyy                                                ",
   "             x   xx!!!!!                                                                                              ",
   "             x    x!!!!!                                                                                              ",
   "             x    x!!!!!                                                                                              ",
   "             xx   x!!!!!                                                                                              ",
   "             x    x!!!!!                                                                                              ",
   "                  x!!!!!                                                                                              ",
   "  o               x!!!!!                                                                                              ",
   "xxxxx            xx!!!!!                       o                                                                      ",
   "xxxxx  xxx|xxxxxxxx!!!!!                                                                                              ",
   "               !!!!!!!!!                      xx                          ^                                           ",
   "               !!!!!!!!!                                                       !                                      ",
   "     @         !!!!!!!!!                 xx                                                                           ",
   "    xxx        !!!!!!!!!x                                                                                             ",
   "!!!!x x!!!|!!!!!!!!!!!!!x  xxxxxxx    x!!!!!!!!!!          =     x   xxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x!!!!!!!!!!!!!!!!!x         xx  xxxxxxxxxxxx  o o  xx                                x   x                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!x                                                                  x o x                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!x                           xxxxxx                                 xxxxx                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!xx o  !                                                                                       ",
   "!!!!x x!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxx!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                               ",
   "                                                                                                                               ",
   "                                                                                                                               ",
   "                                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                                          x=    ooooooooooooooooooooooooooooooox               ",
   "                                                                          x     ooooooooooooooooooooooooooooooox               ",
   "                                                                          x     ooooooooooooooooooooooooooooooox               ",
   "                                                                          x     ooooooooooooooooooooooooooooooxx               ",
   "                                                                          x     ooooooooooooooooooooooooooooooxx               ",
   "                                                                          xx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                                          x     x                                              ",
   "                                                                          x     x                                              ",
   "                                                                          x    xx                                              ",
   "                                                                          x     x                                              ",
   "                                                                          x     x                                              ",
   "                                                                          xx    x                                              ",
   "                                                                          x     x                                              ",
   "                                                        xxx               x    xx                                              ",
   "                                                        x!x               x     x                                              ",
   "              yyy         yy       yyyyyyy              xvx               x     x                                              ",
   "                                                                          x     x                                              ",
   "                                                                          xx    x                                              ",
   "                                                                                x                                              ",
   "                                                                                x                                              ",
   "                                                                               xx                                              ",
   "                                                                           xxxxxx                                              ",
   "                                                                                                                               ",
   "                                                                                                                               ",
   "                    yy  yy                                        xxxxx!!!!!!!!!!!!!!!!!!!!!!!!                                ",
   "                    yyyyyyy                                     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          ",
   "                                                        xxx    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
   "                                                                                                                               ",
   "                                                     o                                                                         ",
   "    yyyy                                             x                                                                         ",
   "   yyyyyyy                                                                                                                     ",
   "                                             !   xx                                                                            ",
   "                                                                                                                               ",
   "                        o                 xx                                                                                   ",
   "                                                                                                                               ",
   "                                                                                                                               ",
   "                      oxxxo                                                                                                    ",
   "                     ox    xo        xx                                                           ^                            ",
   "                     xxo   xx                                                                                                  ",
   "        @              xxxx      !                                                          o                                  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                       !!!|!!!                                ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "            xxxxxxx                xxxxxxx                                                                    ",
   "            x  o  x                x  o x   xxxvxxx                                                           ",
   "            x  o  x      xvx      x  o  x   x     x                                                           ",
   "             x  o  x    x   x    x  o  x    x     x         xxxxx                                             ",
   "              x  o  x   x   x   x  o  x     x     x         x o x xxxxxxxxxxxxx                               ",
   "               x  o  x  x   x  x o   x      x     x         x o x x     o      xx                             ",
   "                x  o  xxx   xxx o   x       x  o  x         x o  x  o      o   xx                             ",
   "                 x                 x        x  o  x         xx   x             xx                             ",
   "                  x               xxxxxxxxxxx     xxxxxxxxxxx           !      xx                             ",
   "                  x                                                          ^  x                             ",
   "                  x=                                             x             ox                             ",
   "  xxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                        x                                                                                     ",
   "   @                    x                                                                                     ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                                                                                              ",
    "                                                                                                              ",
    "                                                                                          x                   ",
    "x       x                                                                                 x                   ",
    " x     x    xxxxxxxxx  x       x              x                x                          x                   ",
    "  x   x     x       x  x       x               x              x   xxxxxxxxxx  xxxxxxxxx   x                   ",
    "   x x      x       x  x       x                x     xx     x    x        x  x        x  x                   ",
    "    x       x       x  x       x                 x   x  x   x     x        x  x        x  x                   ",
    "    x       xxxxxxxxx  xxxxxxxxx                  x x    x x      x        x  x        x                      ",
    "    x                                              x      x       xxxxxxxxxx  x        x  x                   ",
    "    x                                                                                                         ",
    "                                                                                                      x       ",
    "  @                                                                                                   x       ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
